#!/usr/bin/perl
my @elements = (
    { Symbol => "H", Name => "Hydrogen" },
    { Symbol => "He", Name => "Helium" },
    { Symbol => "Li", Name => "Lithium" },
    { Symbol => "Be", Name => "Beryllium" },
    { Symbol => "B", Name => "Boron" },
    { Symbol => "C", Name => "Carbon" },
    { Symbol => "N", Name => "Nitrogen" },
    { Symbol => "O", Name => "Oxygen" },
    { Symbol => "F", Name => "Fluorine" },
    { Symbol => "Ne", Name => "Neon" },
    { Symbol => "Na", Name => "Sodium" },
    { Symbol => "Mg", Name => "Magnesium" },
    { Symbol => "Al", Name => "Aluminium" },
    { Symbol => "Si", Name => "Silicon" },
    { Symbol => "P", Name => "Phosphorus" },
    { Symbol => "S", Name => "Sulfur" },
    { Symbol => "Cl", Name => "Chlorine" },
    { Symbol => "Ar", Name => "Argon" },
    { Symbol => "K", Name => "Potassium" },
    { Symbol => "Ca", Name => "Calcium" },
    { Symbol => "Sc", Name => "Scandium" },
    { Symbol => "Ti", Name => "Titanium" },
    { Symbol => "V", Name => "Vanadium" },
    { Symbol => "Cr", Name => "Chromium" },
    { Symbol => "Mn", Name => "Manganese" },
    { Symbol => "Fe", Name => "Iron" },
    { Symbol => "Co", Name => "Cobalt" },
    { Symbol => "Ni", Name => "Nickel" },
    { Symbol => "Cu", Name => "Copper" },
    { Symbol => "Zn", Name => "Zinc" },
    { Symbol => "Ga", Name => "Gallium" },
    { Symbol => "Ge", Name => "Germanium" },
    { Symbol => "As", Name => "Arsenic" },
    { Symbol => "Se", Name => "Selenium" },
    { Symbol => "Br", Name => "Bromine" },
    { Symbol => "Kr", Name => "Krypton" },
    { Symbol => "Rb", Name => "Rubidium" },
    { Symbol => "Sr", Name => "Strontium" },
    { Symbol => "Y", Name => "Yttrium" },
    { Symbol => "Zr", Name => "Zirconium" },
    { Symbol => "Nb", Name => "Niobium" },
    { Symbol => "Mo", Name => "Molybdenum" },
    { Symbol => "Tc", Name => "Technetium" },
    { Symbol => "Ru", Name => "Ruthenium" },
    { Symbol => "Rh", Name => "Rhodium" },
    { Symbol => "Pd", Name => "Palladium" },
    { Symbol => "Ag", Name => "Silver" },
    { Symbol => "Cd", Name => "Cadmium" },
    { Symbol => "In", Name => "Indium" },
    { Symbol => "Sn", Name => "Tin" },
    { Symbol => "Sb", Name => "Antimony" },
    { Symbol => "Te", Name => "Tellurium" },
    { Symbol => "I", Name => "Iodine" },
    { Symbol => "Xe", Name => "Xenon" },
    { Symbol => "Cs", Name => "Caesium" },
    { Symbol => "Ba", Name => "Barium" },
    { Symbol => "La", Name => "Lanthanum" },
    { Symbol => "Ce", Name => "Cerium" },
    { Symbol => "Pr", Name => "Praseodymium" },
    { Symbol => "Nd", Name => "Neodymium" },
    { Symbol => "Pm", Name => "Promethium" },
    { Symbol => "Sm", Name => "Samarium" },
    { Symbol => "Eu", Name => "Europium" },
    { Symbol => "Gd", Name => "Gadolinium" },
    { Symbol => "Tb", Name => "Terbium" },
    { Symbol => "Dy", Name => "Dysprosium" },
    { Symbol => "Ho", Name => "Holmium" },
    { Symbol => "Er", Name => "Erbium" },
    { Symbol => "Tm", Name => "Thulium" },
    { Symbol => "Yb", Name => "Ytterbium" },
    { Symbol => "Lu", Name => "Lutetium" },
    { Symbol => "Hf", Name => "Hafnium" },
    { Symbol => "Ta", Name => "Tantalum" },
    { Symbol => "W", Name => "Tungsten" },
    { Symbol => "Re", Name => "Rhenium" },
    { Symbol => "Os", Name => "Osmium" },
    { Symbol => "Ir", Name => "Iridium" },
    { Symbol => "Pt", Name => "Platinum" },
    { Symbol => "Au", Name => "Gold" },
    { Symbol => "Hg", Name => "Mercury" },
    { Symbol => "Tl", Name => "Thallium" },
    { Symbol => "Pb", Name => "Lead" },
    { Symbol => "Bi", Name => "Bismuth" },
    { Symbol => "Po", Name => "Polonium" },
    { Symbol => "At", Name => "Astatine" },
    { Symbol => "Rn", Name => "Radon" },
    { Symbol => "Fr", Name => "Francium" },
    { Symbol => "Ra", Name => "Radium" },
    { Symbol => "Ac", Name => "Actinium" },
    { Symbol => "Th", Name => "Thorium" },
    { Symbol => "Pa", Name => "Protactinium" },
    { Symbol => "U", Name => "Uranium" },
    { Symbol => "Np", Name => "Neptunium" },
    { Symbol => "Pu", Name => "Plutonium" },
    { Symbol => "Am", Name => "Americium" },
    { Symbol => "Cm", Name => "Curium" },
    { Symbol => "Bk", Name => "Berkelium" },
    { Symbol => "Cf", Name => "Californium" },
    { Symbol => "Es", Name => "Einsteinium" },
    { Symbol => "Fm", Name => "Fermium" },
    { Symbol => "Md", Name => "Mendelevium" },
    { Symbol => "No", Name => "Nobelium" },
    { Symbol => "Lr", Name => "Lawrencium" },
    { Symbol => "Rf", Name => "Rutherfordium" },
    { Symbol => "Db", Name => "Dubnium" },
    { Symbol => "Sg", Name => "Seaborgium" },
    { Symbol => "Bh", Name => "Bohrium" },
    { Symbol => "Hs", Name => "Hassium" },
    { Symbol => "Mt", Name => "Meitnerium" },
    { Symbol => "Ds", Name => "Darmstadtium" },
    { Symbol => "Rg", Name => "Roentgenium" },
    { Symbol => "Cn", Name => "Copernicium" },
    { Symbol => "Uut", Name => "Ununtrium" },
    { Symbol => "Fl", Name => "Flerovium" },
    { Symbol => "Uup", Name => "Ununpentium" },
    { Symbol => "Lv", Name => "Livermorium" },
    { Symbol => "Uus", Name => "Ununseptium" },
    { Symbol => "Uuo", Name => "Ununoctium" }
);

print "[How many Protons does the atom have?][What is the atomic number of the atom?]\n: ";
chomp ($number = <STDIN>);

print @elements[$number]{Symbol};


##
#	unless @ARGV > 0;
#
#for my $element (@ARGV) {
#	my $index = $element - 1;
#	if ($index < 0 || $index > $#elements) {
#		print "Error: $element \033[31mNOT FOUND\033[m\n";
#		next;
#	}
#	if ($element !~ /^\d+$/) {
#		print "Error: \033[31mWTF\033[m am I supposed to do with $element?\n";
#		next;
#	}
#	print "Element number $element: Symbol: $elements[$index]{Symbol}, Name: $elements[$index]{Name}\n";
#}
